DIM-Squad/Grace-Shopper

package-lock.json, package.json, script/seed.js
As models are created, we will uncomment lines 84-88.
=> Seed 8 - this didn't associate itself - I think I did need the "#"

package-lock.json, package.json
Also removed betas on the babel packages (only non-breaking changes between the betas and the final packages)
=> updated package.json to fix WARNings

server/db/models/user.js
here is Users table. If you think I should add something else to it let me know
=> users table

server/db/models/artist.js, server/db/models/artist.spec.js
please go trough my test file carefully and make sure it makes sense :)
=> artist table and tests

server/db/models/category.js, server/db/models/index.js, server/db/models/review.js, server/db/models/review.spec.js
=> Review model, test and a few validation changes

package-lock.json, server/db/models/user.js, server/db/models/user.spec.js
---
Updated user fields with stringent validations and added a virtual `fullName` field
=> Updated user model with field validations

script/seed.js, server/api/product.js, server/db/models/index.js, server/db/models/order.js, server/db/models/order.spec.js, server/db/models/product.js, server/db/models/product.spec.js
=> Create order model #26

server/api/product.js, server/db/models/index.js, server/db/models/product.js, server/db/models/product.spec.js
* [X ] added unit tests (or none needed)
* [X ] written relevant docs (or none needed)
* [ X] referenced any relevant issues (or none exist)
=> Create product model #13

client/components/user-home.spec.js, package.json, script/seed.js, server/api/index.js, server/api/users.spec.js, server/db/models/category.spec.js, server/db/models/index.js, server/db/models/order.spec.js, server/db/models/product.spec.js, server/db/models/review.spec.js, server/db/models/user.spec.js
---
Fixed broken data model association tests at this time.
=> Create associations #22

server/db/models/index.js, server/db/models/lineItem.js, server/db/models/lineItem.spec.js, server/db/models/user.spec.js
=> Write line item model #23

client/components/ProductCollection.js, client/components/index.js, client/routes.js, client/store/index.js, client/store/products.js, server/db/models/index.js
=> All products component #37

script/seed.js, server/api/product.js, server/db/models/lineItem.js, server/db/models/lineItem.spec.js
=> can seed line items

server/api/products.js, server/api/products.spec.js
---
Single product contains review and reviewers information and its functionality has been tested.
=> Get product reviews and the reviewers details

client/store/selectedProduct.js, client/store/selectedProduct.spec.js, server/api/products.spec.js
---
Created the Selected Product Reducer with tests.
Removed the `only` from `describe.only` I had previously left on the `api` product test file `products.spec.js`
=> Selected Product Reduced with tests

server/db/models/artist.js, server/db/models/product.js, server/db/models/user.js
---
Added avgRating field to User, Artist and Product models
=> Add avgRating field to User, Artist and Product models

script/seed.js, server/db/models/lineItem.js, server/db/models/order.js, server/db/models/product.js
=> db schema and seed now whole cents

package-lock.json, package.json
=> moved chancjs to regular dep

client/routes.js
=> fixed front-end routes so single product works

client/components/ProductDetail.js, client/components/Review.js, script/seed.js, server/api/products.js, server/db/models/product.js, server/db/models/review.js
---
Single Product Page without Add Review or Edit Product capabilities
=> Single Product Page without Add Review or Edit Product capabilities

script/seed.js
Heroku was going to revoke our db priveleges because our db was too big! This fixes that.
=> Shrink db seed

client/components/index.js, package-lock.json, server/api/artist.js, server/api/categories.js, server/api/products.js, server/api/users.js, server/auth/isSelfOrAdmin.js, server/db/models/product.js, server/db/models/user.js
=> Admin post routes #94

client/components/CartItem.js, client/components/ProductDetail.js, client/components/index.js, client/components/navbar.js, client/store/cart.js, server/api/users.js
it is not completely done yet (and not perfect) but working
=> Finishing cart #103

client/components/CartItem.js, client/components/CategoryDropdown.js, client/components/ProductCollection.js, client/components/ProductDetail.js, client/components/SearchBar.js, script/seed.js
=> Styles #109

client/components/CategoryDropdown.js, client/components/ProductCollection.js, client/components/SearchBar.js, client/store/cart.js
these are just few additions to padding and margins..nothing serious :)
=> additional touches on style

README.md, client/components/AddProductForm.js, client/components/ProductCollection.js, client/components/UserCollection.js, server/api/categories.js, server/api/products.js, server/api/users.js
Closes #104 (just some refinements)
=> Admin dashboard #104

README.md, client/components/user-home.js, client/routes.js, server/api/products.js
=> Unregistered user view products

client/components/ProductDetail.js, client/components/Review.js, client/store/products.js, client/store/selectedProduct.js, server/api/index.js, server/api/reviews.js
=> Post reviews #117

client/components/ProductDetail.js
=> fixed star rating issue"

client/components/UserCollection.js, client/routes.js, client/store/users.js, server/api/users.js, server/db/models/review.js
This implements pagination on users and fixes some routes conflicts
=> Pagination

client/components/auth-form.js, client/components/user-home.js, client/routes.js
---
Added a hidden divider to the top of `auth-form`, `user-home` components as well as pointed `/` to the `user-home` component
=> Landing page #140

client/components/navbar.js, client/components/user-home.js
=> Enabled cart and home on the nav bar for users not logged in

client/components/navbar.js, client/components/user-home.js
=> Navbar edits

client/components/OrderCollectionSubMenu.js
=> minor fix to selection"

client/components/ProductCollection.js, client/components/ProductDetail.js, client/components/navbar.js, client/store/cart.js
=> Indicate add to cart #136

client/components/Cart.js, client/components/CheckoutForm.js
=> Update cart view

script/seed.js
=> fixed seed to not make it decrement quantity on seed
